name: Build Docker Image
on:
  push:
    branches:
      - main
      - docker
jobs:
    test:
      name: tests
      runs-on: ubuntu-latest
      steps:
        - name: unit
          run: ls && npm run test
        - name: e2e
          run: npm run test:e2e
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: login
          id: docker-hub
          env:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}
          run: |
            docker login -u $username -p $password 
        - name: build image
          id: build-docker-image
          run: docker build . --file Dockerfile --tag fonmolodtsev/cloud-back:latest
        - name: push the docker image
          id: push-docker-image
          run: docker push ${{secrets.DOCKERHUB_USERNAME}}/cloud-back:latest
