name: Build Docker Image
on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Unit Tests Run"]
    types:
      - completed
jobs:
  build:
    name: push docker image to docker hub
    needs: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login
        id: docker-hub
        env:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          docker login -u $username -p $password 
      - name: build image
        id: build-docker-image
        run: docker build . --file Dockerfile --tag fonmolodtsev/cloud-back:latest
      - name: push the docker image
        id: push-docker-image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/cloud-back:latest
  notify-cloud-infra:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Notify cloud-infra pipeline
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GIT_HUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/OWNER/REPO/actions/workflows/WORKFLOW_ID/dispatches \            
          -d '{"ref":"topic-branch"}'
