name: Build Docker Image
on:
  push:
    branches:
      - main
      - yaml
  workflow_run:
    workflows: ["Unit Tests Run"]
    types:
      - completed
jobs:
  build:
    name: push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login
        id: docker-hub
        env:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          docker login -u $username -p $password 
      - name: build image
        id: build-docker-image
        run: docker build . --file Dockerfile --tag fonmolodtsev/cloud-back:latest
      - name: push the docker image
        id: push-docker-image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/cloud-back:latest
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy in cloud-infra
        uses: peter-evans/repository-dispatch@v3 # Используем сторонний action для вызова workflow
        with:
          repository: MolodzeffDanila/cloud-infra  # Замените на имя владельца и репозитория
          ref: refs/heads/main  # Бранч в другом репозитории (например, main)
          workflow: deploy-vps.yaml  # Имя workflow в другом репозитории
          token: ${{ secrets.GIT_HUB_TOKEN }}
